version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/var/lib/postgresql/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ecommerce
